name: Build
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v3
        with:  
          submodules: 'true'
      - name: Install base package
        run: sudo apt update && apt install build-* bc dosfstools iasl mtools \
              nasm python3 python3-distutils python3-pexpect qemu-utils uuid-dev xorriso -y
      - name: Build
        run: bash build_efi_rom.sh && find ./ -name "6-14.rom" -exec cp  {} ./ \;
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          files: 6-14.rom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
