name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      # Step 1: 检出代码
      - uses: actions/checkout@v3
        with:  
          submodules: 'true'

      # Step 2: 安装构建所需的软件包
      - name: Install base package
        run: |
          sudo apt update && sudo apt install build-* bc dosfstools iasl mtools nasm \
          python3 python3-distutils python3-pexpect qemu-utils uuid-dev xorriso -y

      # Step 3: 构建 ROM 文件
      - name: Build
        run: |
          bash build_efi_rom.sh
          mkdir -p artifacts
          find ./ -name "*.rom" -exec cp {} ./artifacts/ \;

      # Step 4: 上传工件
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: intel6-14roms
          path: artifacts/*

      # Step 5: 获取当前时间
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDD-HHmmSS
          utcOffset: "+08:00"

      # Step 6: 动态生成文件列表
      - name: Generate file list for release
        run: |
          FILE_LIST=$(find artifacts -type f -name "*.rom" | tr '\n' ',')
          echo "Files to upload: $FILE_LIST"
          echo "file_list=$FILE_LIST" >> $GITHUB_ENV

      # Step 7: 创建 GitHub Release
      - name: Create GitHub Releases
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ format('v{0}', steps.current-time.outputs.formattedTime) }}
          release_name: ${{ format('build-{0}', steps.current-time.outputs.formattedTime) }}
          body: |
            New Build
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: 上传 ROM 文件到 Release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/6-14.rom
          overwrite: true
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/pc-4-5.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/pc-6-7-8-9.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/j4125.rom
          overwrite: true
       
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/pc-10.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/pc-11.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/pc-12-13-14.rom
          overwrite: true
       
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/11-J6412.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/11-n5095.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/12-1240p.rom
          overwrite: true
       
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/12-n100.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/N2930.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/N3350.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/nb-11-11700h.rom
          overwrite: true
       
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/nb-11-1185G7E.rom
          overwrite: true
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/nb-12-12700h.rom
          overwrite: true
 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/nb-13-13700h.rom
          overwrite: true       
      
   
       
